# Generated by Django 5.1.6 on 2025-03-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productservices', '0001_initial'),
        ('stocklocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('signal_qty', models.IntegerField()),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('added_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_stock', to=settings.AUTH_USER_MODEL)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_stock', to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocklocation', to='stocklocations.location')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_id_products', to='productservices.products')),
            ],
        ),
    ]
