# Generated by Django 5.1.6 on 2025-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_signal_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='signal_qty',
            field=models.IntegerField(default=10),
        ),
    ]
