# Generated by Django 5.1.6 on 2025-03-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_quantity'),
        ('productservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_id_products', to='productservices.products', unique=True),
        ),
    ]
