# Generated by Django 5.1.6 on 2025-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_purchasebill_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('CREATED', 'CREATED'), ('APPROVED', 'APPROVED'), ('SENT', 'SENT'), ('RECEIVED', 'RECEIVED'), ('PARTIAL RECEIVED', 'PARTIAL RECEIVED'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED'), ('COMPLETE', 'COMPLETE')], default='DRAFT', max_length=255),
        ),
    ]
